[tool.black]
line-length = 120
target-version = ["py39"]

[tool.flake8]
max-line-length = 120
exclude = [".venv", ".git", "__pycache__"]
extend-ignore = ["E203", "E501"] # E203 (whitespace before ':'), E501 (line too long, handled by black)